# Generated by Django 5.2.3 on 2025-06-20 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('skills', models.JSONField(default=list, help_text='List of skills')),
                ('experience_years', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('happy_clients', models.IntegerField(default=0)),
                ('satisfaction_rate', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web Design'), ('content', 'Content Writing'), ('graphic', 'Graphic Design'), ('logo', 'Logo Design'), ('translation', 'Translation'), ('marketing', 'Digital Marketing')], max_length=20)),
                ('icon_class', models.CharField(help_text='FontAwesome icon class (e.g., fas fa-laptop-code)', max_length=50)),
                ('features', models.JSONField(default=list, help_text='List of service features')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='FreelancePro', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.CharField(max_length=200)),
                ('hero_description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_behance', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_position', models.CharField(max_length=100)),
                ('client_company', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
