# Generated by Django 5.2.3 on 2025-06-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('web', 'Web Design'), ('content', 'Content Writing'), ('graphic', 'Graphic Design'), ('logo', 'Logo Design'), ('translation', 'Translation'), ('marketing', 'Digital Marketing'), ('notes', 'Notes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='SkillGrid', max_length=100),
        ),
    ]
