# Generated by Django 5.2.3 on 2025-06-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('web-design', 'Web Design'), ('content-writing', 'Content Writing'), ('graphic-design', 'Graphic Design'), ('logo-design', 'Logo Design'), ('translation', 'Translation'), ('other', 'Other')], max_length=20)),
                ('budget', models.CharField(blank=True, choices=[('under-500', 'Under $500'), ('500-1000', '$500 - $1,000'), ('1000-2500', '$1,000 - $2,500'), ('2500-5000', '$2,500 - $5,000'), ('over-5000', 'Over $5,000')], max_length=20)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
