# Generated by Django 5.2.3 on 2025-06-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='service',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='No subject', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
